definitions:
  # where your page definitions are hosted ('local', 'remote' or 'ensemble')
  from: ensemble

  # for embedding definitions and assets locally with your App
  local:
    # directory where all your Apps definitions/assets reside
    path: ensemble/apps/helloApp

    # appHome is the name of the home screen. This will be the first screen your App will load
    appHome: Hello Home

    # always use this locale for your App instead of using the system-detected locale
    # forcedLocale: en

    # translation settings
    i18n:
      # Directory where all the translation files (e.g. en.yaml, es.yaml) reside.
      # Translation will be disabled without the path.
      path: ensemble/i18n
      # This is not a setting but rather a way to surface the list of all supported languages
      # to the users at runtime (e.g. user can change the App's language based on this list).
      # Keep this in sync with all the languages you have translations for.
      languages: ['en', 'es', 'nl']
      # When a language is missing a translation key, we will try to look it up from this fallback translation.
      # Make sure this fallback language has all the translation keys.
      fallbackLanguage: en

  # for hosting definitions on your own server
  remote:
    # the URL to your remote server where definitions/assets are hosted
    path: <your_http_server_hosting_the_definitions>

    # the home screen for your App
    appHome: Hello Home

    # always use this locale for your App instead of using the system-detected locale
    # forcedLocale: en

    i18n:
      # The URL where all the translation files (e.g. en.yaml, es.yaml) reside.
      # Translation will be disabled without the path.
      path: <your_http_server>
      # This is not a setting but rather a way to surface the list of all supported languages
      # to the users at runtime (e.g. user can change the App's language based on this list).
      # Keep this in sync with all the languages you have translations for.
      languages: [ 'en', 'es', 'nl' ]
      # When a language is missing a translation key, we will try to look it up from this fallback translation.
      # Make sure this fallback language has all the translation keys.
      fallbackLanguage: en

  # for Ensemble-hosted definitions, simply enter your Ensemble's app key
  ensemble:
    # appId can be found on Ensemble Studio. Navigate to your app, click the menu icon on top right, and copy your appId
    # here is the appId for Ensemble Kitchen sink. You can view this app under demo apps in studio.
    appId: wvN7BLPl0cCiKvv2VG14
    # appId: pSEzKcaT6F0DUO7E6IOP

services:

# override any environment variables on studio.ensembleui.com here
# e.g. load local assets instead of URL
environmentVariables:
  # Environment variables can have any value you want and are referenced by {env.myVariable}.
  # Here we use it to demonstrate loading assets locally, overriding the environment variables
  # defined in your App on studio.ensembleui.com.
  # This asset value is empty, meaning a reference of {env.exampleAssetVariable}pic.png
  # will be loaded locally from /ensemble/assets/pic.png
  assets:

# uncomment the following when using firebase analytics.
# For iOS - Make sure that GoogleService-Info.plist is placed under the ios/Runner folder AND has been added to the Xcode project. Just putting the file under Runner folder is NOT sufficient, it has to be added to the prject using Xcode.
# For Android - Make sure that google-services.json is placed under android/app folder
# For Web - make sure that the web config is present under account/firebase/web below.
analytics:
  provider: firebase
  enabled: true
  enableConsoleLogs: true
# uncomment the following when using Firebase analytics for the Web and replace the values with the values from your Firebase app.
accounts:
  firebase:
    android:
      apiKey: "AIzaSyCGhJNYzPva9H_jrg7y6APusgPIiQz0aW4"
      projectId: 'kpn-home-725de'
      storageBucket: 'kpn-home-725de.appspot.com'
      messagingSenderId: '105316420553'
      appId: '1:105316420553:android:a3e86579f4f3d024f3b618'
      measurementId: 'G-180KBPF335'
    ios:
      apiKey: 'AIzaSyC4D_BKOSBI3qt1jidSmo3Yiag8jrQpE04'
      projectId: 'kpn-home-725de'
      storageBucket: 'kpn-home-725de.appspot.com'
      messagingSenderId: '105316420553'
      appId: '1:105316420553:ios:849d5432ae83f6d3f3b618'
      measurementId: 'G-180KBPF335'
